export const UPDATED_CARD_SEARCH = "UPDATED_CARD_SEARCH";
export const CARD_RETRIEVED = "CARD_RETRIEVED";
export const CARD_RETRIEVE_FAILED = "CARD_RETRIEVE_FAILED";

export const DECK_EDITOR_STATUS_CHANGE = "DECK_EDITOR_STATUS_CHANGE";

export const DECK_RECEIVED = "DECK_RECEIVED";
export const DECK_UPDATED = "DECK_UPDATED";

export const DECREMENT_CARD = "DECREMENT_CARD";
export const INCREMENT_CARD = "INCREMENT_CARD";

export const FIRST_ORDER_CHANGE = "FIRST_ORDER_CHANGE";
export const SECOND_ORDER_CHANGE = "SECOND_ORDER_CHANGE";

export const ADD_FILTER = "ADD_FILTER";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const RESET_DECK_EDITOR = "RESET_DECK_EDITOR";
