export const TEST_GAME_CHANGE_STATUS = "TEST_GAME_CHANGE_STATUS";
export const TEST_GAME_DECKS_LOADED = "TEST_GAME_DECKS_LOADED";
export const UPDATE_TEST_GAME = "UPDATE_TEST_GAME";
export const CHANGED_CARD_VIEW = "CHANGED_CARD_VIEW";
