export const ALL_DECKS_STATUS_CHANGE = "ALL_DECKS_STATUS_CHANGE";
export const DECKS_LOADED = "DECKS_LOADED';"
export const USER_DECKS_RECEIVED = "USER_DECKS_RECEIVED";
export const DECK_DELETED = "DECK_DELETED";
